### PR TITLE
Proposition to use linters. Some code cleanup to show what it can be like.

### PR DESCRIPTION
**Pull request by smgladkovskiy**
- Adding mutex to locales map because of concurrent map read-write;
- Code cleaning up by linter rules;
- Some README about contributing;
- Test with parallel execution not working because of locales. Need to change design.

### CODE REVIEW

**Comment by smgladkovskiy** [comment]
@carlosforero up

**Comment by carlosforero** [comment]
@smgladkovskiy It looks nice, I will check out the details later today.

**Comment by smgladkovskiy** [comment]
Hi!

@carlosforero, I've made [sketches of changes for concurrent-safety implementation](https://github.com/cohesivestack/valgo/compare/master...smgladkovskiy:valgo:concurrent_safe?expand=1), but they are based on this linter refactoring. Btw, I reverted my changes with type assertion checking there.

**Comment by carlosforero** [comment]
Dear Sergey.

Thank you for taking the time to submit your PR and for providing valuable ideas to improve the code and release [v0.2.0](https://github.com/cohesivestack/valgo/releases/tag/v0.2.0). I appreciate your efforts to contribute to the project.

However, I'm sorry to say that I'm not able to merge your PR at this time. Reviewing large commits is often difficult and time-consuming, and I think it would be more helpful if you could break it down into smaller and more manageable chunks.

Regarding the use of the linter library, while I agree that it can improve code quality and maintainability, I'm not yet sure about its implementation. The type of linters to use is a very opinionated topic, and I want to be careful in choosing the right one that works best for the project. For now, I want to stick with `go fmt` as it helps maintain a consistent and readable code format, as outlined in our [Contribution Guidelines](https://github.com/cohesivestack/valgo#github-code-contribution-guide). I plan to introduce a linter at a later time, when we receive more feedback from the community.

Once again, I appreciate your contributions to the project, and I hope that you will continue to participate and share your ideas with us in the future.

**Pull request closed without merging**
